<%@ Page Title="" Language="C#" MasterPageFile="~/cwc.master" AutoEventWireup="true" CodeFile="Statistics.aspx.cs" Inherits="Statistics" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Java Slider, Thumbnail Slider" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine12/style.css" />
	<script type="text/javascript" src="engine12/jquery.js"></script>

    <style type="text/css">
        .auto-style65 {
            height: 41px;
        }
        .auto-style66 {
            height: 35px;
        }
    </style>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
       
    <div style="width:100%;height:500px">
        <table class="auto-style2" style="height: 145px">
            <tr>
                <td class="auto-style66"></td>
                <td class="auto-style66"></td>
                <td class="auto-style66"></td>
            </tr>
            <tr>
                <td class="auto-style65"></td>
                <td class="auto-style65">
        <asp:Label ID="Label1" runat="server" Font-Size="XX-Large" Text="Statistics-" Font-Bold="True" Font-Names="AR JULIAN" Font-Underline="True" ForeColor="#000066"></asp:Label>
                </td>
                <td class="auto-style65"></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data12/images/crime_type_by_day_of_week.jpg" alt="Crime Type By Day Of Week" title="Crime Type By Day Of Week" id="wows1_0"/></li>
<li><img src="data12/images/crime_type_timeline.jpg" alt="Crime Type Timeline" title="Crime Type Timeline" id="wows1_1"/></li>
<li><img src="data12/images/frequency_of_crime.jpg" alt="Frequency Of Crime" title="Frequency Of Crime" id="wows1_2"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="Crime Type By Day Of Week"><img src="data12/tooltips/crime_type_by_day_of_week.jpg" alt="Crime Type By Day Of Week"/>1</a>
<a href="#" title="Crime Type Timeline"><img src="data12/tooltips/crime_type_timeline.jpg" alt="Crime Type Timeline"/>2</a>
<a href="#" title="Frequency Of Crime"><img src="data12/tooltips/frequency_of_crime.jpg" alt="Frequency Of Crime"/>3</a>
</div></div>
<span class="wsl"><a href="http://wowslider.com">Gallery Script</a> by WOWSlider.com v4.9</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine12/wowslider.js"></script>
	<script type="text/javascript" src="engine12/script.js"></script>
    </div>
</asp:Content>

